### ISSUE TITLE
create environment in scratch space?

### ISSUE THREAD

**Issue by Roger-luo** [cjdoris/CondaPkg.jl#34]
I'm wondering if it's possible to create the environment in scratch space instead of a separate place managed by CondaPkg. Since if we create the env in scratch space then Pkg's gc can managed those places and delete them when deleting the package. 

currently I notice when I add a package under a package project env, the env is created under the project instead of its scratch space, but I can also see the dependency on `Scratch.jl` so I'm not sure if it actually uses the scratch space.

**Comment by cjdoris** [comment]
Yeah I've thought about this before - I agree it would be nice to let the GC clean these up. The issue with scratch spaces is that if your project doesn't have a UUID (i.e. doesn't have a Project.toml) then the scratch space is put somewhere global. I guess we could use scratch spaces in the case there is a UUID and the current behaviour otherwise.

Scratch.jl is used by MicroMamba.jl to store the package cache (root prefix).

**Comment by cjdoris** [comment]
OK, having thought about the scratch-space idea some more, I've concluded that it doesn't make much sense:
- Most of the time, users work in ordinary projects, which do not have UUIDs, so we cannot use scratch spaces for these.
- The exception is if you're developing a package, which does have a UUID. But in this case, we want different versions of the same package to have different conda environments, because they may have different dependencies. So a single scratch space for all versions of the package is not useful.

So I'll stick with the current behaviour of using a `.CondaPkg` directory under the project directory.

Feel free to reopen if you want to discuss further.

**Comment by cjdoris** [comment]
(I'll also note that if you delete a project, then since the environment is in a subdirectory, then the environment gets deleted too. So I think the original GC motivation wasn't actually going to provide anything new.)
