### ISSUE TITLE
cannot specify any version and build

### ISSUE THREAD

**Issue by t-bltg** [cjdoris/CondaPkg.jl#56]
The following fails (any `version` with `*` and a constrained `build` spec):
```julia
julia> using CondaPkg
pkg> conda add tensorflow=*=cpu*
ERROR: invalid version: "=*=cpu*"
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:35
  [2] validate_version(ver::Any)
    @ CondaPkg [...]/CondaPkg.jl/src/spec.jl:49
  [3] CondaPkg.PkgSpec(name::Any; version::Any, channel::Any, build::Any)
    @ CondaPkg [...]/src/spec.jl:15
  [4] kwcall(::Any, ::Type{CondaPkg.PkgSpec}, name::Any)
    @ CondaPkg [...]/src/spec.jl:13
  [5] parse_pkg(x::String)
    @ CondaPkg.PkgREPL [...]/src/PkgREPL.jl:25
```

The spec is valid since the following works as expected:
```julia
run(CondaPkg.MicroMamba.cmd(`install -y -p [...]/conda/env -c conda-forge tensorflow=\*=cpu\*`))
```

**Comment by cjdoris** [comment]
CondaPkg does not promise (so far) to follow the same package specs as the Conda command line, so it's not a bug that `tensorflow=*=cpu*` is not supported. In fact the CondaPkg REPL syntax is very under-specified right now - sort of intentionally.

For your specific case, you can already do `conda add 'tensorflow >0 cpu*'` or `CondaPkg.add("tensorflow", build="cpu*")`.

On the one hand, it is nice to support familiar syntax for Conda users. On the other hand, the `pkg=version=build` syntax has the drawback that it limits what versions are allowed (e.g. you can't specify the version as `>=3,<4` because those extra `=`s confuse things) and the `pkg=version` syntax is special in that `foo=3.8` actually parses the version as `3.8.*`.

Also, CondaPkg generally tries to stick to conventions from Pkg. So I propose specifying the build with a `#`, e.g. `conda add tensorflow#cpu*`.

What do you think?

**Comment by t-bltg** [comment]
> For your specific case, you can already do conda add 'tensorflow >0 cpu*' or CondaPkg.add("tensorflow", build="cpu*").

Thanks I didn't know that, and it might be worth to add some test or some documentation for the users.

> the pkg=version=build syntax has the drawback that it limits what versions are allowed (e.g. you can't specify the version as >=3,<4 because those extra =s confuse things)

Yes, this is a poor choice from the conda developers.

I would tend to agree with the choice of using `add` instead or `install` for consistency with `Pkg`. In fact, we could use `@1.2` for version specifiers and as you proposed `#cpu*` for a build spec, and try to stick with the [Pkg conventions](https://pkgdocs.julialang.org/v1/repl/#repl-add). Of course, this would need docs.

**Comment by cjdoris** [comment]
FYI #59 implements this suggestion.

**Comment by t-bltg** [comment]
Great, thanks for the prompt fix and the new release ;)
