### ISSUE TITLE
configurable `.toml` deps path

### ISSUE THREAD

**Issue by t-bltg** [cjdoris/CondaPkg.jl#70]
From https://github.com/cjdoris/CondaPkg.jl/issues/66#issuecomment-1403278326, it is unclear why we cannot allow writing to an arbitrary shared file outside (independent of `Base.load_path`, which is per-julia version specific).

> into the topmost project of your load path which depends on CondaPkg

A trivial patch would be something like:
```diff
diff --git a/src/deps.jl b/src/deps.jl
index 12fac1b..5a62a07 100644
--- a/src/deps.jl
+++ b/src/deps.jl
@@ -5,7 +5,7 @@ This is the main `Pkg`-like API, with functions like `add`, `rm`, `status`.
 """

 function cur_deps_file()
-    e = Base.load_path()[1]
+    e = get(ENV, "JULIA_CONDAPKG_DEPS_DIR", Base.load_path()[1])
     if !isdir(e)
         e = dirname(e)
         @assert isdir(e)
```

**Comment by cjdoris** [comment]
The question is... Why?

**Comment by cjdoris** [comment]
If you're aiming to have a shared set of dependencies that all projects can use, you can put them into your global environment (e.g. v1.8) just like you do with ordinary Julia packages. CondaPkg supports environment stacking.

**Comment by t-bltg** [comment]
My use case is multiple julia versions (typical 1.6 lts, 1.8 stable and 1.9 preview), with a different `JULIA_HOME` per binary.
I also use a centralized path in `DEPOT_PATH` typically to share (space consuming) artifacts.

A custom `cur_deps_file` would allow managing only a single `.toml` file.

**Comment by cjdoris** [comment]
I'm going to say no. My justification is that this is functionality that Pkg could provide for Julia packages but doesn't (there's no env var to specify some global Project.toml) and CondaPkg is modelled on Pkg. We all accept that we have different global environments for each minor version of Julia, each with their own set of dependencies.

Also, while it wouldn't be hard to implement, it's not a simple as your one-liner, since `cur_deps_file()` only controls which CondaPkg.toml file is edited by `add` and `rm`, whereas `resolve` looks through `load_path()`.
